# CLASSE = É A BASE PARA O OBJETO
# CLASSE = É UMA DEFINIÇÃO/DESENHO DO O OBJETO EM CONSTRUÇÃO = PLANTA DO APARTAMENTO
# O OBJETO = TUDO QUE FOR MATERIAL/ EX: O APARTAMENTO 
# MÉTODOS/CARACTERISTICAS/COMPORTAMENTOS = OS QUARTOS E AS DIVIOES DA CASA

#EX2:
#CLASSE: CACHORRO
#ATRIBUTOS: TAMANHO, COR, RAÇA, PESO
#MÉTODOS: LATIR, COMER, MORDER 