# ESCOPO: DEFINE ONDE UMA VARIÁVEL ESTARÁ DISPONÍVEL DENTRO DO SEU PROGRAMA.

# TEMOS 4 TIPOS EM RUBY
# 1. LOCAIS: ACESSADA APENAS ONDE FORAM CRIADAS / USA-SE LETRAS MINÚSCULAS OU SUBLINHADA
# 2. GLOBAIS: ACESSADA DE QUALQUER LOCAL / USA-SE O PREFIXO $
# 3. CLASSES: ACESSADA DE QUALQUER LUGAR DA CLASSE // USA-SE @@
# 4. INTÂNCIA: SEMELHANTE A CLASSE / USA-SE @